### ISSUE TITLE
Hello everyone. 

### ISSUE THREAD

**Issue by Nstripeik** [Nstripeik/CIS-264-team-2-project#1]

**Comment by OtakuWest** [comment]
Hello

**Comment by Nstripeik** [comment]
Hey guys sorry about not get to this sooner. I had lets say a very interesting weekend.  
Anyway our project is to create a library catalog system. At the barest minimum a user need to been to input the name of books and app will return all the details about the book. Everything after that is brownie points. 
 

There are a couple part a database and book class both of which are already created or a least the script to make the database exist. two views, one for enter the book or ID and another for displaying the details. The view where data is put in will require validation  This may be one view with a partial view displaying the details of the books. also we need a way to query the database. 

Personally my weakest point is figuring out how to query the database.  My guess we probably would have to use Linq but feel free to correct me.  

Before I divide up the workload between us. does us anyone have a preference as to what they work on?

**Comment by OtakuWest** [comment]
I'll take a look at the code at a later time today since I have work this morning, and I'll see what I can do about what needs to be done. As for querying, I do believe Linq would definitely be the way to go on that one since its the closest to actual querying through a database.
